# Generated by Django 2.1.1 on 2018-11-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('u_password', models.CharField(max_length=200)),
                ('u_email', models.CharField(max_length=60)),
                ('u_shou_address', models.CharField(max_length=200)),
                ('u_postcode', models.CharField(max_length=6)),
                ('u_phone', models.CharField(max_length=11)),
            ],
        ),
    ]
