# Generated by Django 2.1.1 on 2018-11-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_title', models.CharField(max_length=20, verbose_name='商品名称')),
                ('g_pic', models.ImageField(upload_to='df_goods', verbose_name='商品图片')),
                ('g_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='商品价格')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('g_unit', models.CharField(default='500g', max_length=20, verbose_name='商品计价')),
                ('g_click', models.IntegerField(verbose_name='商品浏览量')),
                ('g_abstract', models.CharField(max_length=200, verbose_name='商品简介')),
                ('g_stock', models.IntegerField(verbose_name='商品库存')),
                ('g_content', models.TextField(verbose_name='商品详情')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='分类标题')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fs_goods.TypeInfo', verbose_name='所属分类'),
        ),
    ]
